name: Build ReflectMaster APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8' # Hạ xuống Java 8 để tương thích với dự án cũ

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK 成品
        uses: actions/upload-artifact@v4
        with:
          name: ReflectMaster-APK
          path: "**/build/outputs/apk/debug/*.apk"
          
